In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
arr_2d = np.array([[3,4,5],
                   [7,8,9],
                   [1,2,6]])
print(arr1 * arr2)
print("Array size : ", arr.size)
print("arrays dimention : ", arr.ndim)
print(arr_2d)
print(arr_2d[1,1])

[ 6 14 24 36  0]
Array size :  5
arrays dimention :  1
[[3 4 5]
 [7 8 9]
 [1 2 6]]
8


In [5]:
# Slicing function in NumPy
import numpy as np 
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[1:7:2])
print(arr[:7:]) #only end
print(arr[::2]) #only step
print(arr[1::],"\n") #only start
M = np.array([[3,4,5],
              [7,8,9],
              [1,2,6]])
print(M[1:3,1:3]) # [R,C] R-> 1:3 = 1,2 | C-> 1:3 = 1,2

[20 40 60]
[10 20 30 40 50 60 70]
[10 30 50 70 90]
[20 30 40 50 60 70 80 90]


In [6]:
# Data type One data type to another data type
import numpy as np 
arr1 = np.array([1,2.4,3,4,5])
arr2 = np.array([6,7,8,9,0])
arr = arr1 + arr2
# print("Normal :",arr)
print("Using astype :",arr.astype('i')) # float to int
a = np.array([1,0,3])
print(a.astype(bool)) # int to boolean

Using astype : [ 7  9 11 13  5]
[ True False  True]


In [7]:
import numpy as np 
range_arr = np.arange(10,100,10)
print(range_arr)

lin_arr = np.linspace(0,100,3)
print(lin_arr)

[10 20 30 40 50 60 70 80 90]
[  0.  50. 100.]


In [8]:
import numpy as np 
range_arr = np.arange(10,100,10)
print(range_arr)

lin_arr = np.linspace(10,100,10) # Divid equal parts 
print(lin_arr)

[10 20 30 40 50 60 70 80 90]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [1]:
import pandas as pd
import numpy as np
# df = pd.read_csv("day2/sample.csv")
# print(df)
arr = np.array([[1,2,3],
                [4,5,6]])
data = {"id": [1,2,3,4],
      "name": ["logeshwari","kanagaraj","loki","logeshwaran"],
      "age": [18,31,999,99],
      "location": ["chennai","vannarupettai","Asgard","vannarupettai"],
      "Status": ["Housewife","Director","God of story","VIP"]}
df = pd.DataFrame(data)
print(df)

   id         name  age       location        Status
0   1   logeshwari   18        chennai     Housewife
1   2    kanagaraj   31  vannarupettai      Director
2   3         loki  999         Asgard  God of story
3   4  logeshwaran   99  vannarupettai           VIP
